In [1]:
!pip install numpy

In [12]:
import numpy as np
import sys

### 1. Array Creation and Properties

#### 1.1 Array Creation Methods

In [3]:
price_list = [21000, 56900, 100, 21, 0]
price_array = np.array(price_list)

In [4]:
print(f"From list: {price_list}")
print(f"From array: {price_array}")

From list: [21000, 56900, 100, 21, 0]
From array: [21000 56900   100    21     0]


In [5]:
print (f"Shape {price_array.shape}")

Shape (5,)


In [8]:
price_list = [[21000], [56900], [100], [21], [0]]
price_array = np.array(price_list)
print(f"From list: {price_list}")
print(f"From array: {price_array}")
print (f"Shape {price_array.shape}")

From list: [[21000], [56900], [100], [21], [0]]
From array: [[21000]
 [56900]
 [  100]
 [   21]
 [    0]]
Shape (5, 1)


In [9]:
price_list = [[21000, 56900, 100, 21, 0]]
price_array = np.array(price_list)
print(f"From list: {price_list}")
print(f"From array: {price_array}")
print (f"Shape {price_array.shape}")

From list: [[21000, 56900, 100, 21, 0]]
From array: [[21000 56900   100    21     0]]
Shape (1, 5)


#### 1.2 Memory

In [13]:
size= 10000
python_list = list(range(size))
numpy_array = np.arange(size)

In [16]:
list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(i) for i in python_list)
array_memory = numpy_array.nbytes + numpy_array.__sizeof__()

print(f"List memory {list_memory}")
print(f"Array memory {array_memory}")

List memory 360056
Array memory 160112


#### 1.3 Vectorization

In [39]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

a_list * 3, a_array * 3

([1, 2, 3, 1, 2, 3, 1, 2, 3], array([3, 6, 9]))

[1 1 1 1 1 1]

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

[[1 1 1 1 1 1]]

In [40]:
a = np.ones(6)
b = np.ones((6, 1))
c = np.ones((1, 6))

ac = a + c
ab = a + b
bc = b + c

In [42]:
ac, ab, bc

(array([[2., 2., 2., 2., 2., 2.]]),
 array([[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]]),
 array([[2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2.]]))

There are 3 students

- Isuru (70, 60 ,50 ,40)
- Kawshi (40, 50, 20, 10)
- Lochana (90, 90, 80, 70)

4 Subjects
- Maths
- Science
- History
- Health

4 Weights
- 0.5
- 0.4
- 0.07
- 0.03

In [60]:
isuru = np.array([70, 60, 50, 40])
kawshi = np.array([40, 50, 20, 10])
lochana = np.array([90, 90, 80, 70])

weights = np.array([0.5, 0.4, 0.07, 0.03])

students = np.array([isuru, kawshi, lochana])

In [46]:
students * weights

array([[35. , 24. ,  3.5,  1.2],
       [20. , 20. ,  1.4,  0.3],
       [45. , 36. ,  5.6,  2.1]])

students -> 3 x 4
weights -> (4,)


In [55]:
students @ weights.reshape(4, 1)

array([[63.7],
       [41.7],
       [88.7]])